# The URL of your website.
# End your URL with a `/` trailing slash, e.g. `https://example.com/`.
baseurl : "http://fubicy.org/pau/"
relativeURLs : true
canonifyURLs : true
# Title of your site
title : "Pau à Vélo"
author : "Pau à Vélo"
theme : "blank"
paginate: 12

related:
  threshold: 80
  includeNewer: true
  toLower: true
  indices:
    - name: "author"
      toLower: true
      weight: 30
    - name: "tags"
      weight: 100
    - name: "date"
      weight: 10
      pattern: "2006"

menu:
  main:
    - name: "Agenda"
      url: "/#agenda"
    - name: "Blog"
      url: "/#blog"
    - name: "Services"
      url: "/#services"
    - name: "À propos"
      url: "/#a-propos"
