# The URL of your website.
# End your URL with a `/` trailing slash, e.g. `https://example.com/`.
baseurl = "http://fubicy.org/pau/"
relativeURLs = true
# canonifyURLs  = true
# Title of your site
title = "Pau à Vélo"
author = "Pau à Vélo"
theme = "blank"

[params]
#  homePostCount = 6
