[build]
  publish = "public"
  command = "rm -r public && hugo --gc"

[context.production.environment]
  HUGO_VERSION = "0.55.6"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"
  HUGO_BASEURL = "http://www.pauavelo.fr/"

[context.branch-deploy]
  command = "hugo -D -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
  HUGO_VERSION = "0.55.6"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"
