[build]
  publish = "public"
  command = "hugo"

[context.production.environment]
  HUGO_VERSION = "0.55.0"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"
  # HUGO_BASEURL = "http://wwww.pauavelo.fr/"

[context.branch-deploy]
  command = "hugo -D -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
  HUGO_VERSION = "0.55.0"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"
